# Usa un'immagine di base con Python
FROM python:3.9-slim

# Imposta la directory di lavoro
WORKDIR /db

# Copia il codice nell'immagine
COPY . /db

# Installa le dipendenze
RUN pip install -r requirements.txt

# Esponi la porta sulla quale l'app ascolta
EXPOSE 5004

# Avvia l'app Flask
CMD ["python3", "db.py"]
