version: '3.8'

services:
  web:
    build: .
    ports:
      - "5004:5004"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accademia
    ports:
      - "5433:5432" #cambio la porta esterna
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
